[project]
name = "Tracs"
version = "0.1.0"
description = "Code for paper: TraCS: Trajectory Collection in Continuous Space under Local Differential Privacy"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "pandas-stubs~=3.0.0",
]
